package com.wl.util.model;

import java.io.Serializable;

public class ReconReq implements Serializable{

	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*Generated by Wl in QR*/
	private String TransId;
	/*original RRN. Sent in CallBack*/
	private String rrn;
	private String transStatus;
	private String payerAddr;
	private String payeeAddr;
	private String transDateTime;
	private String MCC;
	private String error="";
	/*WL generated refund txn id*/
	private String txnRefundId;
	/*Can be full or partial*/
	private double amount;
	/*Shared by WL duing onboarding*/
	private String merchantId;
	/*Sent by Bank in callback API*/
	private String gatewayTransId;
	private String mobileNo;
	private String refundTXNDate;
	
	//Added for Sbi Refund Request
	private String transRefNo;
	private String customerRefNo;
	private String orderNo;
	private String refundRemark;
	
	/**
	 * @return the merchantId
	 */
	public String getMerchantId() {
		return merchantId;
	}
	/**
	 * @param merchantId the merchantId to set
	 */
	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}
	
	
	/**
	 * @return the payerAddr
	 */
	public String getPayerAddr() {
		return payerAddr;
	}
	/**
	 * @param payerAddr the payerAddr to set
	 */
	public void setPayerAddr(String payerAddr) {
		this.payerAddr = payerAddr;
	}
	/**
	 * @return the payeeAddr
	 */
	public String getPayeeAddr() {
		return payeeAddr;
	}
	/**
	 * @param payeeAddr the payeeAddr to set
	 */
	public void setPayeeAddr(String payeeAddr) {
		this.payeeAddr = payeeAddr;
	}
	/**
	
	
	
	/**
	 * @return the mCC
	 */
	public String getMCC() {
		return MCC;
	}
	/**
	 * @param mCC the mCC to set
	 */
	public void setMCC(String mCC) {
		MCC = mCC;
	}
	
	public ReconReq() {
		super();
	}
	/**
	 * @return the error
	 */
	public String getError() {
		return error;
	}
	/**
	 * @param error the error to set
	 */
	public void setError(String error) {
		this.error = error;
	}
	/**
	 * @return the txnRefundId
	 */
	public String getTxnRefundId() {
		return txnRefundId;
	}
	/**
	 * @param txnRefundId the txnRefundId to set
	 */
	public void setTxnRefundId(String txnRefundId) {
		this.txnRefundId = txnRefundId;
	}
	/**
	 * @return the amount
	 */
	public double getAmount() {
		return amount;
	}
	/**
	 * @param amount the amount to set
	 */
	public void setAmount(double amount) {
		this.amount = amount;
	}
	
	/**
	 * @return the gatewayTransId
	 */
	public String getGatewayTransId() {
		return gatewayTransId;
	}
	/**
	 * @param gatewayTransId the gatewayTransId to set
	 */
	public void setGatewayTransId(String gatewayTransId) {
		this.gatewayTransId = gatewayTransId;
	}
	/**
	 * @return the mobileNo
	 */
	public String getMobileNo() {
		return mobileNo;
	}
	/**
	 * @param mobileNo the mobileNo to set
	 */
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}
	/**
	 * @return the transId
	 */
	public String getTransId() {
		return TransId;
	}
	/**
	 * @param transId the transId to set
	 */
	public void setTransId(String transId) {
		TransId = transId;
	}
	/**
	 * @return the rrn
	 */
	public String getRrn() {
		return rrn;
	}
	/**
	 * @param rrn the rrn to set
	 */
	public void setRrn(String rrn) {
		this.rrn = rrn;
	}
	/**
	 * @return the transStatus
	 */
	public String getTransStatus() {
		return transStatus;
	}
	/**
	 * @param transStatus the transStatus to set
	 */
	public void setTransStatus(String transStatus) {
		this.transStatus = transStatus;
	}
	/**
	 * @return the transDateTime
	 */
	public String getTransDateTime() {
		return transDateTime;
	}
	/**
	 * @param transDateTime the transDateTime to set
	 */
	public void setTransDateTime(String transDateTime) {
		this.transDateTime = transDateTime;
	}
	/**
	 * @return the refundTXNDate
	 */
	public String getRefundTXNDate() {
		return refundTXNDate;
	}
	/**
	 * @param refundTXNDate the refundTXNDate to set
	 */
	public void setRefundTXNDate(String refundTXNDate) {
		this.refundTXNDate = refundTXNDate;
	}
	
	public String getCustomerRefNo() {
		return customerRefNo;
	}
	public void setCustomerRefNo(String customerRefNo) {
		this.customerRefNo = customerRefNo;
	}
	
	public String getOrderNo() {
		return orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
		
	public String getRefundRemark() {
		return refundRemark;
	}
	public void setRefundRemark(String refundRemark) {
		this.refundRemark = refundRemark;
	}
	
	public String getTransRefNo() {
		return transRefNo;
	}
	public void setTransRefNo(String transRefNo) {
		this.transRefNo = transRefNo;
	}
	
	@Override
	public String toString() {
		return "ReconReq [TransId=" + TransId + ", rrn=" + rrn + ", transStatus=" + transStatus + ", payerAddr="
				+ payerAddr + ", payeeAddr=" + payeeAddr + ", transDateTime=" + transDateTime + ", MCC=" + MCC
				+ ", error=" + error + ", txnRefundId=" + txnRefundId + ", amount=" + amount + ", merchantId="
				+ merchantId + ", gatewayTransId=" + gatewayTransId + ", mobileNo=" + mobileNo + ", refundTXNDate="
				+ refundTXNDate + ", transRefNo=" + transRefNo + ", customerRefNo=" + customerRefNo + ", orderNo="
				+ orderNo + ", refundRemark=" + refundRemark + "]";
	}
	
}
