//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 03:08:58 PM IST 
//


package com.wl.upi.pnb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://com/fss/upi}MerchantStatusUpdateReq"/>
 *         &lt;element ref="{http://com/fss/upi}MerchantStatusUpdateResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "merchantStatusUpdateReq",
    "merchantStatusUpdateResponse"
})
@XmlRootElement(name = "Body", namespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class Body {

    @XmlElement(name = "MerchantStatusUpdateReq", required = true)
    protected MerchantStatusUpdateReq merchantStatusUpdateReq;
    @XmlElement(name = "MerchantStatusUpdateResponse", required = true)
    protected MerchantStatusUpdateResponse merchantStatusUpdateResponse;

    /**
     * Gets the value of the merchantStatusUpdateReq property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantStatusUpdateReq }
     *     
     */
    public MerchantStatusUpdateReq getMerchantStatusUpdateReq() {
        return merchantStatusUpdateReq;
    }

    /**
     * Sets the value of the merchantStatusUpdateReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantStatusUpdateReq }
     *     
     */
    public void setMerchantStatusUpdateReq(MerchantStatusUpdateReq value) {
        this.merchantStatusUpdateReq = value;
    }

    /**
     * Gets the value of the merchantStatusUpdateResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantStatusUpdateResponse }
     *     
     */
    public MerchantStatusUpdateResponse getMerchantStatusUpdateResponse() {
        return merchantStatusUpdateResponse;
    }

    /**
     * Sets the value of the merchantStatusUpdateResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantStatusUpdateResponse }
     *     
     */
    public void setMerchantStatusUpdateResponse(MerchantStatusUpdateResponse value) {
        this.merchantStatusUpdateResponse = value;
    }

}
