//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 03:08:58 PM IST 
//


package com.wl.upi.pnb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wl.upi.pnb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SubMerchantID_QNAME = new QName("java:com.fss.upi.req", "SubMerchantID");
    private final static QName _ResCode_QNAME = new QName("java:com.fss.upi.req", "ResCode");
    private final static QName _TerminalID_QNAME = new QName("java:com.fss.upi.req", "TerminalID");
    private final static QName _ResDesc_QNAME = new QName("java:com.fss.upi.req", "ResDesc");
    private final static QName _MerchantID_QNAME = new QName("java:com.fss.upi.req", "MerchantID");
    private final static QName _PayerCode_QNAME = new QName("java:com.fss.upi.req", "PayerCode");
    private final static QName _OrgTxnRefId_QNAME = new QName("java:com.fss.upi.req", "OrgTxnRefId");
    private final static QName _TimeStamp_QNAME = new QName("java:com.fss.upi.req", "TimeStamp");
    private final static QName _TxnRefId_QNAME = new QName("java:com.fss.upi.req", "TxnRefId");
    private final static QName _OrgTxnId_QNAME = new QName("java:com.fss.upi.req", "OrgTxnId");
    private final static QName _TxnId_QNAME = new QName("java:com.fss.upi.req", "TxnId");
    private final static QName _TxnType_QNAME = new QName("java:com.fss.upi.req", "TxnType");
    private final static QName _PayerVirAddr_QNAME = new QName("java:com.fss.upi.req", "PayerVirAddr");
    private final static QName _PayeeMobileNumber_QNAME = new QName("java:com.fss.upi.req", "PayeeMobileNumber");
    private final static QName _OrgTxnTimeStamp_QNAME = new QName("java:com.fss.upi.req", "OrgTxnTimeStamp");
    private final static QName _Amount_QNAME = new QName("java:com.fss.upi.req", "Amount");
    private final static QName _PayeeVirAddr_QNAME = new QName("java:com.fss.upi.req", "PayeeVirAddr");
    private final static QName _PayeeCode_QNAME = new QName("java:com.fss.upi.req", "PayeeCode");
    private final static QName _CurrencyCode_QNAME = new QName("java:com.fss.upi.req", "CurrencyCode");
    private final static QName _Remarks_QNAME = new QName("java:com.fss.upi.req", "Remarks");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wl.upi.pnb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link MerchantStatusUpdateReq }
     * 
     */
    public MerchantStatusUpdateReq createMerchantStatusUpdateReq() {
        return new MerchantStatusUpdateReq();
    }

    /**
     * Create an instance of {@link Req }
     * 
     */
    public Req createReq() {
        return new Req();
    }

    /**
     * Create an instance of {@link UPI }
     * 
     */
    public UPI createUPI() {
        return new UPI();
    }

    /**
     * Create an instance of {@link MerchantStatusUpdateResponse }
     * 
     */
    public MerchantStatusUpdateResponse createMerchantStatusUpdateResponse() {
        return new MerchantStatusUpdateResponse();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link Resp }
     * 
     */
    public Resp createResp() {
        return new Resp();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Envelope }
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "SubMerchantID")
    public JAXBElement<String> createSubMerchantID(String value) {
        return new JAXBElement<String>(_SubMerchantID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "ResCode")
    public JAXBElement<String> createResCode(String value) {
        return new JAXBElement<String>(_ResCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "TerminalID")
    public JAXBElement<String> createTerminalID(String value) {
        return new JAXBElement<String>(_TerminalID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "ResDesc")
    public JAXBElement<String> createResDesc(String value) {
        return new JAXBElement<String>(_ResDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "MerchantID")
    public JAXBElement<String> createMerchantID(String value) {
        return new JAXBElement<String>(_MerchantID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "PayerCode")
    public JAXBElement<String> createPayerCode(String value) {
        return new JAXBElement<String>(_PayerCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "OrgTxnRefId")
    public JAXBElement<String> createOrgTxnRefId(String value) {
        return new JAXBElement<String>(_OrgTxnRefId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "TimeStamp")
    public JAXBElement<String> createTimeStamp(String value) {
        return new JAXBElement<String>(_TimeStamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "TxnRefId")
    public JAXBElement<String> createTxnRefId(String value) {
        return new JAXBElement<String>(_TxnRefId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "OrgTxnId")
    public JAXBElement<String> createOrgTxnId(String value) {
        return new JAXBElement<String>(_OrgTxnId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "TxnId")
    public JAXBElement<String> createTxnId(String value) {
        return new JAXBElement<String>(_TxnId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "TxnType")
    public JAXBElement<String> createTxnType(String value) {
        return new JAXBElement<String>(_TxnType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "PayerVirAddr")
    public JAXBElement<String> createPayerVirAddr(String value) {
        return new JAXBElement<String>(_PayerVirAddr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "PayeeMobileNumber")
    public JAXBElement<String> createPayeeMobileNumber(String value) {
        return new JAXBElement<String>(_PayeeMobileNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "OrgTxnTimeStamp")
    public JAXBElement<String> createOrgTxnTimeStamp(String value) {
        return new JAXBElement<String>(_OrgTxnTimeStamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "Amount")
    public JAXBElement<String> createAmount(String value) {
        return new JAXBElement<String>(_Amount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "PayeeVirAddr")
    public JAXBElement<String> createPayeeVirAddr(String value) {
        return new JAXBElement<String>(_PayeeVirAddr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "PayeeCode")
    public JAXBElement<String> createPayeeCode(String value) {
        return new JAXBElement<String>(_PayeeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "CurrencyCode")
    public JAXBElement<String> createCurrencyCode(String value) {
        return new JAXBElement<String>(_CurrencyCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:com.fss.upi.req", name = "Remarks")
    public JAXBElement<String> createRemarks(String value) {
        return new JAXBElement<String>(_Remarks_QNAME, String.class, null, value);
    }

}
