//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 03:08:58 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/fss/upi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns={@XmlNs(prefix="soapenv", namespaceURI="http://schemas.xmlsoap.org/soap/envelope/"),@XmlNs(prefix="java", namespaceURI="java:com.fss.upi.req"),
		@XmlNs(prefix="upi", namespaceURI="http://com/fss/upi")})
package com.wl.upi.pnb;

import javax.xml.bind.annotation.XmlNs;
