//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 03:08:58 PM IST 
//


package com.wl.upi.pnb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{java:com.fss.upi.req}OrgTxnId"/>
 *         &lt;element ref="{java:com.fss.upi.req}TxnId"/>
 *         &lt;element ref="{java:com.fss.upi.req}OrgTxnRefId"/>
 *         &lt;element ref="{java:com.fss.upi.req}ResCode"/>
 *         &lt;element ref="{java:com.fss.upi.req}ResDesc"/>
 *         &lt;element ref="{java:com.fss.upi.req}TimeStamp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orgTxnId",
    "txnId",
    "orgTxnRefId",
    "resCode",
    "resDesc",
    "timeStamp"
})
@XmlRootElement(name = "Resp", namespace = "java:com.fss.upi.req")
public class Resp {

    @XmlElement(name = "OrgTxnId", namespace = "java:com.fss.upi.req", required = true)
    protected String orgTxnId;
    @XmlElement(name = "TxnId", namespace = "java:com.fss.upi.req", required = true)
    protected String txnId;
    @XmlElement(name = "OrgTxnRefId", namespace = "java:com.fss.upi.req", required = true)
    protected String orgTxnRefId;
    @XmlElement(name = "ResCode", namespace = "java:com.fss.upi.req", required = true)
    protected String resCode;
    @XmlElement(name = "ResDesc", namespace = "java:com.fss.upi.req", required = true)
    protected String resDesc;
    @XmlElement(name = "TimeStamp", namespace = "java:com.fss.upi.req", required = true)
    protected String timeStamp;

    /**
     * Gets the value of the orgTxnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgTxnId() {
        return orgTxnId;
    }

    /**
     * Sets the value of the orgTxnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgTxnId(String value) {
        this.orgTxnId = value;
    }

    /**
     * Gets the value of the txnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnId(String value) {
        this.txnId = value;
    }

    /**
     * Gets the value of the orgTxnRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgTxnRefId() {
        return orgTxnRefId;
    }

    /**
     * Sets the value of the orgTxnRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgTxnRefId(String value) {
        this.orgTxnRefId = value;
    }

    /**
     * Gets the value of the resCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * Sets the value of the resCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResCode(String value) {
        this.resCode = value;
    }

    /**
     * Gets the value of the resDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResDesc() {
        return resDesc;
    }

    /**
     * Sets the value of the resDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResDesc(String value) {
        this.resDesc = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

}
