//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 03:08:58 PM IST 
//


package com.wl.upi.pnb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{java:com.fss.upi.req}TxnId"/>
 *         &lt;element ref="{java:com.fss.upi.req}MerchantID"/>
 *         &lt;element ref="{java:com.fss.upi.req}SubMerchantID"/>
 *         &lt;element ref="{java:com.fss.upi.req}TerminalID"/>
 *         &lt;element ref="{java:com.fss.upi.req}TxnRefId"/>
 *         &lt;element ref="{java:com.fss.upi.req}TimeStamp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "txnId",
    "merchantID",
    "subMerchantID",
    "terminalID",
    "txnRefId",
    "timeStamp"
})
@XmlRootElement(name = "UPI", namespace = "java:com.fss.upi.req")
public class UPI {

    @XmlElement(name = "TxnId", namespace = "java:com.fss.upi.req", required = true)
    protected String txnId;
    @XmlElement(name = "MerchantID", namespace = "java:com.fss.upi.req", required = true)
    protected String merchantID;
    @XmlElement(name = "SubMerchantID", namespace = "java:com.fss.upi.req", required = true)
    protected String subMerchantID;
    @XmlElement(name = "TerminalID", namespace = "java:com.fss.upi.req", required = true)
    protected String terminalID;
    @XmlElement(name = "TxnRefId", namespace = "java:com.fss.upi.req", required = true)
    protected String txnRefId;
    @XmlElement(name = "TimeStamp", namespace = "java:com.fss.upi.req", required = true)
    protected String timeStamp;

    /**
     * Gets the value of the txnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnId(String value) {
        this.txnId = value;
    }

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the subMerchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMerchantID() {
        return subMerchantID;
    }

    /**
     * Sets the value of the subMerchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMerchantID(String value) {
        this.subMerchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the txnRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnRefId() {
        return txnRefId;
    }

    /**
     * Sets the value of the txnRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnRefId(String value) {
        this.txnRefId = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

}
